description: 'Configure the AI Lakera Guard plugin to reveal or conceal the failure reason to clients.'


title: 'Inspect requests only with ai-lakera-guard to inspect responses'

weight: 900

requirements: 
  - You have a Lakera account and an API key.

variables:
  lakera_api_key:
    description: 'The API key for your Lakera account.'
    value: $LAKERA_API_KEY
  project_id: 
    description: "The Lakera project identifier used to evaluate the request."
    value: $LAKERA_PROJECT

config:
  api_key:  ${lakera_api_key}
  project_id: ${project_id}
  reveal_failure_categories: true

min_version:
  gateway: '3.13'

tools:
  - deck
  - admin-api
  - konnect-api
  - kic
  - terraform